version: "3"


services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db_network
    env_file:
      - .env
    depends_on:
      - portfoliomysql
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portfoliomysql:
    image: mysql:latest
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: "${PORTFOLIO_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${PORTFOLIO_DB_NAME}"
      MYSQL_USER: "${PORTFOLIO_DB_USER}"
      MYSQL_PASSWORD: "${PORTFOLIO_DB_PASSWORD}"
    volumes:
      - "mysql_data:/var/lib/mysql"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  db_network:
    driver: bridge

volumes:
  mysql_data:
