version: "3"

# dev mysql container
services:
  mysql:
    image: mysql:latest
    #    networks:
    #      - db_network
    ports: # Exposes MySQL on localhost for development
      - "${PORTFOLIO_DB_EXPOSED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${PORTFOLIO_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${PORTFOLIO_DB_NAME}"
      MYSQL_USER: "${PORTFOLIO_DB_USER}"
      MYSQL_PASSWORD: "${PORTFOLIO_DB_PASSWORD}"
    volumes:
      - "mysql_data:/var/lib/mysql"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#networks:
#  db_network:
#    driver: bridge

volumes:
  mysql_data:
